apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app-consumer
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: flask-app-consumer
    spec:
      containers:
        - name: flask-app-consumer
          image: FLASK_APP
          envFrom:
            - configMapRef:
                name: flask-app-consumer-env
            - secretRef:
                name: flask-app-consumer-secrets
